add db scripts
dvpnt/dvpntjs-scripts pull request #3
Opened 2020-04-30 13:52 UTC by eloim-zubkov

2020-05-12 13:41 UTC, eloim-zubkov commented
ping @fleg

2020-05-12 13:43 UTC, eloim-zubkov commented on lib/db.js
> +			dbName,
не решили проблему
restore с флагом --create не создает базу, приходится делать это отдельно. Проблем нет, кроме передачи параметров для создания createParams: encoding, template, lc-collate и lc-ctype

2020-05-12 13:53 UTC, eloim-zubkov commented on lib/db.js
> +const {program} = require('commander');
сделано под commander 4 версии https://github.com/dvpnt/dvpntjs-scripts/pull/2

2020-05-13 07:15 UTC, fleg requested changes
я бы все таки оставил на классах-адаптерах, и вынес бы их в lib, могут добавиться новые субд, и все в одном файле держать не очень удобно

2020-05-13 07:15 UTC, fleg commented on lib/db.js
> +}
парсинг ссылки можно сделать независимым от субд
```
Welcome to Node.js v12.16.1.
Type ".help" for more information.
> new URL('mongodb://foo:bar@localhost:456/erty')
URL {
  href: 'mongodb://foo:bar@localhost:456/erty',
  origin: 'null',
  protocol: 'mongodb:',
  username: 'foo',
  password: 'bar',
  host: 'localhost:456',
  hostname: 'localhost',
  port: '456',
  pathname: '/erty',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
> 

```

2020-05-13 07:15 UTC, fleg commented on lib/db.js
> +	] = parsePostgresUrl(dbUrl);
тут вроде в одну строку влазит

2020-05-13 07:15 UTC, fleg commented on lib/db.js
> +		{env: {
так вроде договорились не делать

2020-05-13 07:15 UTC, fleg commented on lib/db.js
> +		);
здесь весь вызов в одну строку влазит

2020-05-13 15:33 UTC, fleg requested changes

2020-05-13 15:33 UTC, fleg commented on lib/db/index.js
> +#!/usr/bin/env node
shebang нужен только в файлах, который запускаются, в данном случае только bin/db

2020-05-13 15:33 UTC, fleg commented on lib/db/index.js
> +const dbTypesHash = {mongo, postgres};
dbmsHash

2020-05-13 15:33 UTC, fleg commented on lib/db/index.js
> +		type: _.initial(url.protocol).join('')
dbms

2020-05-13 15:33 UTC, fleg commented on lib/db/index.js
> +		type: _.initial(url.protocol).join('')
`url.protocol.slice(0, -1)`

2020-05-13 15:33 UTC, fleg commented on lib/db/index.js
> +		dbName: url.pathname.slice(1),
db

2020-05-13 15:33 UTC, fleg commented on lib/db/postgres.js
> +					PGPORT: port,
через env я бы передавал только пароль, остальное через аргументы (для drop тоже)

2020-05-14 12:36 UTC, fleg approved these changes

2020-05-14 12:36 UTC, merged