add support for es6 in lint-migrations
dvpnt/dvpntjs-scripts pull request #5
Opened 2020-05-15 13:09 UTC by ShanksRH

2020-05-18 06:37 UTC, fleg requested changes

2020-05-18 06:37 UTC, fleg commented on bin/lint-migrations
> +		const importedModule = await import(path.join(migrationsPath, name));
а тут нельзя просто проигнорить эту строку? или ошибка парсинга ломает все?

2020-05-18 06:37 UTC, fleg commented on bin/lint-migrations
> +});
тут я бы сделал одну асинхронную точку входа
```js
async function main() {
// ...
}

main();
```

2020-05-19 14:40 UTC, ShanksRH commented on bin/lint-migrations
> +		const importedModule = await import(path.join(migrationsPath, name));
ломает
![image](https://user-images.githubusercontent.com/49105616/82340226-a4dadc80-99f7-11ea-9135-fefcee706c99.png)

2020-05-20 06:35 UTC, fleg approved these changes

2020-05-20 06:35 UTC, merged